export interface Repository {
  id: string
  name: string
  repo: string
  category: 'fintech' | 'infrastructure' | 'automation' | 'data' | 'product' | 'experiments'
  language: string
  languageColor: string
  stars?: number
  description: string
  problem: string
  architecture: string
  keyDecisions: string[]
  tradeoffs: string
  impact: string
  stack: string[]
  lessonsLearned: string
  url: string
  demo?: string
  planetSize: number
  planetColor: string
  orbitRadius: number
  orbitSpeed: number
}

export interface CareerStage {
  id: string
  title: string
  subtitle: string
  period: string
  description: string
  theme: string
  accentColor: string
  visual: string
}

export interface SkillNode {
  id: string
  label: string
  cluster: string
  level: number
  connections: string[]
}

export const repos: Repository[] = [
  {
    id: 'chapchapsms',
    name: 'ChapChapSMS',
    repo: 'chapchapsms-mvp',
    category: 'fintech',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    description: 'Multi-tenant bulk SMS platform for business communication at scale',
    problem: 'Small businesses in East Africa needed affordable, reliable mass communication infrastructure without complexity',
    architecture: 'Node.js + Express REST API, React dashboard, Africa\'s Talking SMS gateway, LowDB for rapid prototyping, queue-based message dispatch',
    keyDecisions: [
      'Africa\'s Talking over Twilio — 80% cost reduction for African carriers',
      'LowDB for MVP speed — zero infrastructure overhead',
      'Multi-tenant from day one — isolation & billing built-in',
      'Queue architecture — prevents API rate limit failures',
    ],
    tradeoffs: 'LowDB limits to ~10k records; production would migrate to PostgreSQL. Chose speed-to-market over scale.',
    impact: 'Enabled SMEs to dispatch thousands of SMS campaigns. Proved product-market fit for bulk messaging in East Africa.',
    stack: ['Node.js', 'Express', 'React', 'Tailwind CSS', 'Africa\'s Talking', 'LowDB'],
    lessonsLearned: 'Telco API quirks are unpredictable. Always build retry logic and dead-letter queues from day one.',
    url: 'https://github.com/savin2001/chapchapsms-mvp',
    planetSize: 2.2,
    planetColor: '#F7DF1E',
    orbitRadius: 8,
    orbitSpeed: 0.4,
  },
  {
    id: 'chapchap-dashboard',
    name: 'ChapChap Dashboard',
    repo: 'chapchap-dashboard-mvp',
    category: 'fintech',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    description: 'Analytics and operations dashboard for the ChapChapSMS platform',
    problem: 'Operators needed real-time visibility into message delivery, campaign performance, and tenant usage',
    architecture: 'React SPA with charting libraries, polling-based real-time updates, CSV export, multi-tenant filtering',
    keyDecisions: [
      'React SPA for fast iteration — decoupled from API',
      'Polling over WebSockets for MVP simplicity',
      'Tenant-scoped views — privacy by design',
    ],
    tradeoffs: 'Polling adds server load at scale; production upgrade to WebSocket streams.',
    impact: 'Provided operators with campaign insights, delivery rates, and failure analysis.',
    stack: ['React', 'JavaScript', 'Chart.js', 'Tailwind CSS'],
    lessonsLearned: 'Dashboard UX should mirror the user\'s mental model of their operations, not the data schema.',
    url: 'https://github.com/savin2001/chapchap-dashboard-mvp',
    planetSize: 1.5,
    planetColor: '#F0A500',
    orbitRadius: 10,
    orbitSpeed: 0.3,
  },
  {
    id: 'nse-ai-tracker',
    name: 'NSE AI Tracker',
    repo: 'nse-ai-tracker',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'AI-powered tracker for the Nairobi Securities Exchange',
    problem: 'Retail investors lacked accessible, intelligent tools to track and understand NSE market movements',
    architecture: 'TypeScript full-stack, AI analysis layer for market signals, automated data ingestion from NSE feeds',
    keyDecisions: [
      'TypeScript end-to-end — type safety across data pipeline',
      'AI analysis layer — turns raw data into actionable insights',
      'Local-first data — reduces dependency on unreliable external APIs',
    ],
    tradeoffs: 'NSE data access is restricted; had to build scrapers with legal constraints in mind.',
    impact: 'Democratized market intelligence for retail investors on the Nairobi bourse.',
    stack: ['TypeScript', 'Next.js', 'AI/ML', 'Node.js'],
    lessonsLearned: 'Financial data pipelines need extreme validation. A single wrong number loses user trust permanently.',
    url: 'https://github.com/savin2001/nse-ai-tracker',
    planetSize: 2.0,
    planetColor: '#3178C6',
    orbitRadius: 13,
    orbitSpeed: 0.25,
  },
  {
    id: 'gamified-devops',
    name: 'Gamified DevOps RPG',
    repo: 'Gamified-DevOps-RPG',
    category: 'infrastructure',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'RPG game that teaches DevOps concepts through interactive storytelling',
    problem: 'DevOps learning is abstract and dry. Engineers struggle to connect CI/CD theory to real-world practice.',
    architecture: 'TypeScript game engine, scenario-based progression system, real DevOps concepts embedded in gameplay mechanics',
    keyDecisions: [
      'RPG genre — highest engagement for technical learning',
      'Scenario-based — mimics real on-call and deployment situations',
      'Progressive complexity — starts simple, mirrors real DevOps maturity',
    ],
    tradeoffs: 'Game fidelity vs. educational accuracy tension. Chose education first, gameplay second.',
    impact: 'Novel approach to DevOps education. Merges entertainment with operational training.',
    stack: ['TypeScript', 'React', 'Game Logic', 'GSAP'],
    lessonsLearned: 'Gamification works when the game mechanics themselves mirror the target skill, not just wrap it.',
    url: 'https://github.com/savin2001/Gamified-DevOps-RPG',
    planetSize: 2.5,
    planetColor: '#A855F7',
    orbitRadius: 16,
    orbitSpeed: 0.2,
  },
  {
    id: 'summit-nexus',
    name: 'Summit Nexus',
    repo: 'the-summit-nexus',
    category: 'product',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Executive intelligence platform with strategic insights for tech leaders',
    problem: 'Tech executives lacked a single platform aggregating industry signals, competitive intelligence, and strategic frameworks',
    architecture: 'TypeScript + Next.js, AI-driven content aggregation, executive-grade UX, real-time intelligence feeds',
    keyDecisions: [
      'AI curation over manual editorial — scales without editorial team',
      'Executive UX — minimal, dense, no noise',
      'Subscription model — aligns incentives with quality',
    ],
    tradeoffs: 'AI curation risks hallucination; implemented human-review layer for strategic content.',
    impact: 'Provides CTOs and VPs with curated intelligence to make faster, better-informed decisions.',
    stack: ['TypeScript', 'Next.js', 'AI/LLM', 'Tailwind CSS'],
    lessonsLearned: 'Executive products must be ruthlessly focused. Every feature must earn its place in the interface.',
    url: 'https://github.com/savin2001/the-summit-nexus',
    planetSize: 2.8,
    planetColor: '#00F0FF',
    orbitRadius: 19,
    orbitSpeed: 0.15,
  },
  {
    id: 'grant-pilot',
    name: 'Grant Pilot Canada',
    repo: 'grant_pilot_canada',
    category: 'product',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'AI platform demystifying Canadian government grants for SMEs',
    problem: 'Canadian SMEs miss billions in available grants due to complex eligibility, jargon, and fragmented information',
    architecture: 'TypeScript + Next.js, AI eligibility matching engine, grant database with automated updates, application workflow',
    keyDecisions: [
      'AI eligibility matching — no manual browsing of 500+ programs',
      'Plain-language translation — removes government jargon barrier',
      'Workflow automation — handles applications, not just discovery',
    ],
    tradeoffs: 'Grant data changes frequently; automated refresh pipeline is critical infrastructure.',
    impact: 'Helps SMEs discover and apply for grants they would otherwise miss.',
    stack: ['TypeScript', 'Next.js', 'AI/LLM', 'PostgreSQL'],
    lessonsLearned: 'Government data is messy. Budget 3x the time you think for data normalization.',
    url: 'https://github.com/savin2001/grant_pilot_canada',
    planetSize: 2.3,
    planetColor: '#FF6B6B',
    orbitRadius: 22,
    orbitSpeed: 0.12,
  },
  {
    id: 'copper-recycling',
    name: 'Copper Recycling',
    repo: 'copper_recycling',
    category: 'product',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Copper grading solution connecting suppliers and recyclers',
    problem: 'Copper recycling market has opacity problems — grading inconsistency, trust gaps between suppliers and buyers',
    architecture: 'TypeScript marketplace platform, standardized grading system, supplier-buyer matching, transaction transparency',
    keyDecisions: [
      'Standardized grading schema — common language for the market',
      'Two-sided marketplace — solve supply and demand simultaneously',
      'Transparency layer — builds trust through verifiable grading',
    ],
    tradeoffs: 'Physical commodity markets resist digital transformation. Adoption requires field validation.',
    impact: 'Creates efficiency in an opaque physical commodity market.',
    stack: ['TypeScript', 'Next.js', 'Marketplace Logic'],
    lessonsLearned: 'Physical-digital integration requires deep industry trust. The tech is the easy part.',
    url: 'https://github.com/savin2001/copper_recycling',
    planetSize: 1.8,
    planetColor: '#FF8C42',
    orbitRadius: 25,
    orbitSpeed: 0.1,
  },
  {
    id: 'devops-journey',
    name: 'DevOps Learning Journey',
    repo: 'devops-learning-journey',
    category: 'infrastructure',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 4,
    description: 'Documented journey through modern DevOps practices and tooling',
    problem: 'DevOps knowledge is scattered. This is a structured, documented path through real tools and real setups.',
    architecture: 'Python automation scripts, IaC examples, CI/CD templates, monitoring configurations, hands-on exercises',
    keyDecisions: [
      'Document everything — learning is only valuable if transferable',
      'Real tools — no toy examples, actual production-grade configs',
      'Community-first — starred and forked by peers',
    ],
    tradeoffs: 'Breadth vs depth. Chose breadth to create a map, then depth on critical paths.',
    impact: '4 stars, 2 forks — actively used by community for learning.',
    stack: ['Python', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    lessonsLearned: 'Documenting your learning journey compounds knowledge and builds community.',
    url: 'https://github.com/savin2001/devops-learning-journey',
    planetSize: 1.6,
    planetColor: '#3572A5',
    orbitRadius: 28,
    orbitSpeed: 0.08,
  },
  {
    id: 'sme-appointments',
    name: 'SME Appointment App',
    repo: 'sme_appointment_app',
    category: 'product',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    description: 'Operational scheduling platform for small businesses',
    problem: 'SMEs manage appointments through WhatsApp and phone calls — chaotic, error-prone, customer-unfriendly',
    architecture: 'JavaScript CRUD app, calendar integration, SMS/email notifications, availability management, booking workflows',
    keyDecisions: [
      'Simple UX first — SMEs need tools that just work',
      'SMS notifications — meets customers where they are',
      'No-login booking — removes friction for end customers',
    ],
    tradeoffs: 'Simplicity over features. Resisted scope creep for a clean MVP.',
    impact: 'Removes scheduling chaos for service-based SMEs.',
    stack: ['JavaScript', 'Node.js', 'Calendar APIs', 'SMS'],
    lessonsLearned: 'For SME tools, the workflow must match their existing mental model. Change the system, not the user.',
    url: 'https://github.com/savin2001/sme_appointment_app',
    planetSize: 1.4,
    planetColor: '#22C55E',
    orbitRadius: 31,
    orbitSpeed: 0.07,
  },
  {
    id: 'n8n-automation',
    name: 'n8n Automation Stack',
    repo: 'my-n8n-docker',
    category: 'automation',
    language: 'Dockerfile',
    languageColor: '#2496ED',
    description: 'Self-hosted n8n workflow automation stack with Docker',
    problem: 'No-code automation platforms are expensive and lock you into vendor ecosystems',
    architecture: 'Docker Compose n8n stack, PostgreSQL persistence, reverse proxy, automated backup, custom workflow library',
    keyDecisions: [
      'Self-hosted n8n — zero vendor lock-in, data sovereignty',
      'Docker Compose — single-command deployment anywhere',
      'PostgreSQL backend — production-grade workflow storage',
    ],
    tradeoffs: 'Self-hosting requires maintenance. Chose control over convenience.',
    impact: 'Personal automation infrastructure running 50+ workflows.',
    stack: ['Docker', 'n8n', 'PostgreSQL', 'Nginx', 'Bash'],
    lessonsLearned: 'Self-hosted tooling pays dividends. The upfront investment eliminates recurring SaaS costs and vendor dependencies.',
    url: 'https://github.com/savin2001/my-n8n-docker',
    planetSize: 1.7,
    planetColor: '#EA4B71',
    orbitRadius: 34,
    orbitSpeed: 0.06,
  },
  {
    id: 'tax-automation',
    name: 'Tax Automation Platform',
    repo: 'tax-automation-platform',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Compliance platform helping SMEs align with KRA tax requirements',
    problem: 'Kenyan SMEs face KRA compliance complexity without CFOs or tax software — resulting in penalties and legal risk',
    architecture: 'Subscription SaaS, automated tax computation, KRA eTIMS integration, compliance calendar, document generation',
    keyDecisions: [
      'KRA eTIMS integration — direct regulatory compliance',
      'Subscription model — recurring revenue aligns with continuous compliance',
      'Automated generation — removes manual calculation errors',
    ],
    tradeoffs: 'Regulatory APIs are unstable. Built extensive fallback and manual override systems.',
    impact: 'Removes compliance anxiety for SMEs operating in Kenya\'s tax environment.',
    stack: ['TypeScript', 'Next.js', 'KRA eTIMS API', 'PostgreSQL'],
    lessonsLearned: 'RegTech products must be bulletproof. Users trust you with their legal standing.',
    url: 'https://github.com/savin2001',
    planetSize: 2.1,
    planetColor: '#F59E0B',
    orbitRadius: 37,
    orbitSpeed: 0.05,
  },
  {
    id: 'digital-farmers-wallet',
    name: 'Digital Farmers Wallet',
    repo: 'digital-farmers-wallet',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Digital financial platform for agricultural communities',
    problem: 'Kenyan smallholder farmers are financially excluded — no savings vehicles, credit access, or payment rails',
    architecture: 'Mobile-first wallet, M-Pesa integration, savings circles, micro-loan engine, agent banking support',
    keyDecisions: [
      'USSD + smartphone dual interface — serves all phone types',
      'M-Pesa primary rails — where farmers already have money',
      'Agent banking model — trust through local intermediaries',
    ],
    tradeoffs: 'KYC requirements vs accessibility friction. Built tiered verification.',
    impact: 'Financial inclusion for underserved agricultural communities.',
    stack: ['TypeScript', 'React Native', 'M-Pesa API', 'USSD', 'PostgreSQL'],
    lessonsLearned: 'Financial products for underserved communities require radical simplicity and deep cultural understanding.',
    url: 'https://github.com/savin2001',
    planetSize: 2.0,
    planetColor: '#10B981',
    orbitRadius: 40,
    orbitSpeed: 0.045,
  },
  {
    id: 'sacco-ussd',
    name: 'Sacco USSD Platform',
    repo: 'sacco-ussd-platform',
    category: 'fintech',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    description: 'Banking access through low-bandwidth USSD channels for Saccos',
    problem: 'Sacco members in rural Kenya cannot access accounts via smartphone apps — need low-bandwidth channel',
    architecture: 'USSD state machine, Africa\'s Talking USSD gateway, session management, Sacco core banking integration',
    keyDecisions: [
      'USSD state machine architecture — maps perfectly to menu flows',
      'Session-less design — USSD sessions are ephemeral',
      'Core banking adapter pattern — works with multiple Sacco systems',
    ],
    tradeoffs: 'USSD has 182-character limit per screen. Every word must count.',
    impact: 'Extends Sacco banking reach to feature phone users — majority of rural Kenya.',
    stack: ['JavaScript', 'Node.js', 'Africa\'s Talking USSD', 'State Machine'],
    lessonsLearned: 'Constraint-driven design produces the clearest UX. USSD\'s limits force clarity that smartphone apps often lack.',
    url: 'https://github.com/savin2001',
    planetSize: 1.9,
    planetColor: '#8B5CF6',
    orbitRadius: 43,
    orbitSpeed: 0.04,
  },
  {
    id: 'p2p-chama',
    name: 'P2P Chama Platform',
    repo: 'p2p-chama-platform',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Digital group finance platform for traditional Chama circles',
    problem: 'Kenyan Chama groups manage contributions, loans, and disbursements through WhatsApp and paper registers',
    architecture: 'P2P transaction engine, group wallet, contribution tracking, loan management, audit trail, M-Pesa settlement',
    keyDecisions: [
      'Trustless accounting — every transaction cryptographically auditable',
      'Group governance rules — encodes Chama constitutions in code',
      'Mobile-first — group members interact primarily on phones',
    ],
    tradeoffs: 'Social trust vs system trust. Designed for transparency without replacing human relationships.',
    impact: 'Modernizes the Chama system — Kenya\'s grassroots financial backbone.',
    stack: ['TypeScript', 'React Native', 'M-Pesa', 'PostgreSQL'],
    lessonsLearned: 'Group financial products must handle human conflict, not just transactions. Build for disagreements.',
    url: 'https://github.com/savin2001',
    planetSize: 2.0,
    planetColor: '#EC4899',
    orbitRadius: 46,
    orbitSpeed: 0.035,
  },
  {
    id: 'angular-dashboard',
    name: 'Angular Analytics Dashboard',
    repo: 'angular-dashboard-front-end',
    category: 'data',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Data analytics dashboard built with Angular',
    problem: 'Need for a modular, scalable frontend dashboard architecture for data visualization',
    architecture: 'Angular component architecture, RxJS reactive streams, service-based data layer, responsive grid layout',
    keyDecisions: [
      'Angular for enterprise-grade structure and tooling',
      'RxJS for reactive, real-time data handling',
      'Component composition for reusability',
    ],
    tradeoffs: 'Angular\'s learning curve vs long-term maintainability benefits.',
    impact: 'Demonstrates enterprise frontend architecture competency.',
    stack: ['Angular', 'TypeScript', 'RxJS', 'Chart.js'],
    lessonsLearned: 'Reactive programming patterns pay dividends in data-heavy applications.',
    url: 'https://github.com/savin2001/angular-dashboard-front-end',
    planetSize: 1.5,
    planetColor: '#DD0031',
    orbitRadius: 49,
    orbitSpeed: 0.03,
  },
]

export const careerStages: CareerStage[] = [
  {
    id: 'explore',
    title: 'EXPLORE',
    subtitle: 'Curiosity as Infrastructure',
    period: '2019 – 2020',
    description: 'First contact with systems. Learning that software is infrastructure, and infrastructure is everything. Building foundations through experimentation and curiosity.',
    theme: 'from sketches to systems',
    accentColor: '#00F0FF',
    visual: 'sketch',
  },
  {
    id: 'build',
    title: 'BUILD',
    subtitle: 'Code Streams at Scale',
    period: '2020 – 2021',
    description: 'Turning ideas into production systems. First APIs, first databases, first customers. Learning that building is the fastest way to understand.',
    theme: 'from theory to production',
    accentColor: '#3B82F6',
    visual: 'code',
  },
  {
    id: 'operate',
    title: 'OPERATE',
    subtitle: 'Reliability is a Feature',
    period: '2021 – 2022',
    description: 'Systems in production are systems under pressure. Learning monitoring, alerting, incident response, and the discipline of SLOs. Uptime is trust.',
    theme: 'from code to confidence',
    accentColor: '#22C55E',
    visual: 'dashboard',
  },
  {
    id: 'scale',
    title: 'SCALE',
    subtitle: 'Architecture at Volume',
    period: '2022 – 2023',
    description: 'Designing for 10x, 100x growth. Platform engineering, multi-tenant architecture, security at scale, FinTech regulatory compliance. Every decision becomes leverage.',
    theme: 'from product to platform',
    accentColor: '#A855F7',
    visual: 'architecture',
  },
  {
    id: 'create',
    title: 'CREATE',
    subtitle: 'Systems Thinking as Product Design',
    period: '2023 – Now',
    description: 'Combining infrastructure depth with product intuition. Building digital channels, driving reliability engineering, pioneering FinTech solutions. The future is still being written.',
    theme: 'from execution to vision',
    accentColor: '#F59E0B',
    visual: 'future',
  },
]

export const skills: SkillNode[] = [
  // Infrastructure cluster
  { id: 'kubernetes', label: 'Kubernetes', cluster: 'infrastructure', level: 3, connections: ['docker', 'helm', 'terraform', 'observability'] },
  { id: 'docker', label: 'Docker', cluster: 'infrastructure', level: 4, connections: ['kubernetes', 'ci-cd'] },
  { id: 'terraform', label: 'Terraform', cluster: 'infrastructure', level: 3, connections: ['kubernetes', 'aws', 'cloud'] },
  { id: 'helm', label: 'Helm', cluster: 'infrastructure', level: 3, connections: ['kubernetes'] },
  { id: 'ci-cd', label: 'CI/CD', cluster: 'infrastructure', level: 4, connections: ['docker', 'github-actions', 'devops'] },
  { id: 'github-actions', label: 'GitHub Actions', cluster: 'infrastructure', level: 4, connections: ['ci-cd'] },
  // Security cluster
  { id: 'security', label: 'Security', cluster: 'security', level: 4, connections: ['devsecops', 'zero-trust', 'iam'] },
  { id: 'devsecops', label: 'DevSecOps', cluster: 'security', level: 3, connections: ['security', 'ci-cd'] },
  { id: 'zero-trust', label: 'Zero Trust', cluster: 'security', level: 3, connections: ['security', 'iam'] },
  { id: 'iam', label: 'IAM', cluster: 'security', level: 3, connections: ['security', 'aws'] },
  // Cloud cluster
  { id: 'aws', label: 'AWS', cluster: 'cloud', level: 4, connections: ['terraform', 'cloud', 'iam'] },
  { id: 'cloud', label: 'Cloud Architecture', cluster: 'cloud', level: 4, connections: ['aws', 'kubernetes'] },
  // Observability
  { id: 'observability', label: 'Observability', cluster: 'observability', level: 4, connections: ['prometheus', 'grafana', 'reliability'] },
  { id: 'prometheus', label: 'Prometheus', cluster: 'observability', level: 3, connections: ['observability', 'grafana'] },
  { id: 'grafana', label: 'Grafana', cluster: 'observability', level: 3, connections: ['prometheus', 'observability'] },
  { id: 'reliability', label: 'SRE / Reliability', cluster: 'observability', level: 4, connections: ['observability', 'devops'] },
  // Automation
  { id: 'devops', label: 'DevOps', cluster: 'automation', level: 5, connections: ['ci-cd', 'reliability', 'infrastructure', 'python'] },
  { id: 'python', label: 'Python', cluster: 'automation', level: 4, connections: ['devops', 'automation'] },
  { id: 'automation', label: 'Automation', cluster: 'automation', level: 4, connections: ['python', 'n8n'] },
  { id: 'n8n', label: 'n8n', cluster: 'automation', level: 3, connections: ['automation'] },
  // FinTech
  { id: 'fintech', label: 'FinTech', cluster: 'fintech', level: 5, connections: ['mpesa', 'payments', 'ussd', 'compliance'] },
  { id: 'mpesa', label: 'M-Pesa API', cluster: 'fintech', level: 4, connections: ['fintech', 'payments'] },
  { id: 'payments', label: 'Payment Systems', cluster: 'fintech', level: 4, connections: ['fintech', 'mpesa'] },
  { id: 'ussd', label: 'USSD', cluster: 'fintech', level: 3, connections: ['fintech', 'telco'] },
  { id: 'compliance', label: 'Compliance', cluster: 'fintech', level: 3, connections: ['fintech', 'security'] },
  { id: 'telco', label: 'Telco APIs', cluster: 'fintech', level: 3, connections: ['ussd', 'sms'] },
  { id: 'sms', label: 'SMS Gateway', cluster: 'fintech', level: 3, connections: ['telco'] },
  // Architecture
  { id: 'architecture', label: 'Architecture', cluster: 'architecture', level: 5, connections: ['microservices', 'api-design', 'cloud', 'devops'] },
  { id: 'microservices', label: 'Microservices', cluster: 'architecture', level: 4, connections: ['architecture', 'kubernetes'] },
  { id: 'api-design', label: 'API Design', cluster: 'architecture', level: 4, connections: ['architecture', 'nodejs'] },
  // Languages/Frameworks
  { id: 'typescript', label: 'TypeScript', cluster: 'code', level: 5, connections: ['nodejs', 'react', 'nextjs'] },
  { id: 'nodejs', label: 'Node.js', cluster: 'code', level: 5, connections: ['typescript', 'api-design'] },
  { id: 'react', label: 'React', cluster: 'code', level: 4, connections: ['typescript', 'nextjs'] },
  { id: 'nextjs', label: 'Next.js', cluster: 'code', level: 4, connections: ['react', 'typescript'] },
]

export const clusterColors: Record<string, string> = {
  infrastructure: '#00F0FF',
  security: '#FF3B3B',
  cloud: '#3B82F6',
  observability: '#22C55E',
  automation: '#F59E0B',
  fintech: '#A855F7',
  architecture: '#EC4899',
  code: '#F7DF1E',
}

export const metrics = {
  uptime: '99.97%',
  incidents_resolved: '147',
  deployments_shipped: '1,200+',
  systems_monitored: '35+',
  automation_workflows: '50+',
  repos: '66+',
  countries_impacted: '3',
}
