export interface Repository {
  id: string
  name: string
  repo: string
  category: 'fintech' | 'infrastructure' | 'automation' | 'data' | 'product' | 'experiments'
  language: string
  languageColor: string
  stars?: number
  isPrivate?: boolean
  description: string
  problem: string
  architecture: string
  keyDecisions: string[]
  tradeoffs: string
  impact: string
  stack: string[]
  lessonsLearned: string
  url: string
  demo?: string
  planetSize: number
  planetColor: string
  orbitRadius: number
  orbitSpeed: number
}

export interface CareerStage {
  id: string
  title: string
  subtitle: string
  period: string
  description: string
  theme: string
  accentColor: string
  visual: string
}

export interface SkillNode {
  id: string
  label: string
  cluster: string
  level: number
  connections: string[]
}

export interface Service {
  id: string
  title: string
  tagline: string
  description: string
  deliverables: string[]
  industries: string[]
  icon: string
  accentColor: string
}

export const repos: Repository[] = [
  // ─── Active / Private projects ───────────────────────────────────
  {
    id: 'jobyetu',
    name: 'JobSwipe',
    repo: 'jobyetu',
    category: 'product',
    language: 'TypeScript',
    languageColor: '#3178C6',
    isPrivate: true,
    description: 'AI-powered job discovery and auto-application platform. Swipe curated jobs → Claude Sonnet tailors your CV → Playwright auto-applies across Africa, Europe & Australia.',
    problem: 'Job seekers spend 80% of their effort on repetitive applications and CV customisation. Every application demands a unique CV but nobody has time to rewrite for each role.',
    architecture: 'Next.js 14 multi-tenant SaaS. Supabase with per-user RLS (zero cross-user data leakage). Upstash Redis queues. The tailor-agent.ts calls Claude Sonnet (claude-sonnet-4-6) with a strict system prompt that prohibits adding fabricated experience — only reorders, rephrases, and re-emphasises existing CV content. JSON schema validation with retry-on-malformed. Playwright + Apify for headless multi-market apply across BrighterMonday, Fuzu, LinkedIn, eFinancialCareers, and Seek.',
    keyDecisions: [
      'Claude Sonnet for tailoring — model quality directly correlates with interview rate; Sonnet pricing ($3/M input, $15/M output) accepted as product cost',
      'Strict no-fabrication system prompt — legal and ethical requirement; every claim in tailored CV must trace back to original source',
      'Spend guard — per-user daily cap ($0.50) + platform weekly budget ($2 × active users) with security_event logging; 1-in-20 sampling for platform check avoids DB pressure',
      'LLM cost log (llm_cost_log table) — every call persisted with model, tokens, USD cost; admin analytics over 24h/7d/30d windows',
      'Prompt injection test suite (sanitizeLLMInput.test.ts, prompt-injection.spec.ts) — user CV content and job descriptions are sanitised before reaching Claude',
    ],
    tradeoffs: 'Sonnet adds 3–8s latency to tailoring; mitigated by background queueing so users never wait synchronously. Retry-on-bad-JSON adds a second Sonnet call in ~2% of cases — accepted cost.',
    impact: 'Compresses a 3-hour application session into 10 minutes. Multi-market targeting reaches opportunities that region-locked platforms miss.',
    stack: ['TypeScript', 'Next.js 14', 'Claude API (Sonnet)', 'Supabase', 'Playwright', 'Upstash Redis', 'Apify', 'Zod'],
    lessonsLearned: 'AI cost is a product feature, not an ops concern. The spend guard, cost log, and model selection are UX decisions — they\'re what keeps the product affordable at scale.',
    url: 'https://github.com/savin2001/jobyetu',
    planetSize: 2.8,
    planetColor: '#F59E0B',
    orbitRadius: 9,
    orbitSpeed: 0.38,
  },
  {
    id: 'nifc-platform',
    name: 'NIFC Platform',
    repo: 'nifca',
    category: 'product',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    isPrivate: true,
    description: 'Full-stack web platform for the Nairobi International Finance Centre — public site, client portal, and admin portal serving Kenya\'s premier financial hub.',
    problem: 'NIFC needed a professional digital presence, a secure client portal for financial centre applicants, and an internal admin system — built to government-grade reliability standards.',
    architecture: 'Decoupled React 18/Vite 5 frontend + Node.js/Express 4 REST API backend. Public website, authenticated client portal (Google reCAPTCHA v2 + session auth), JWT-secured admin panel. MySQL 8 on backend with Microsoft Graph API for institutional email and node-cron for LinkedIn auto-sync.',
    keyDecisions: [
      'Separate frontend (nifca) / backend (nifca-backend) repos — independent deployments, different CI pipelines',
      'Dual auth model — session-based for clients (persistent login), JWT for staff (stateless, API access)',
      'Microsoft Graph API for email — aligns with NIFC\'s Microsoft 365 environment',
      'LinkedIn auto-sync via node-cron — keeps NIFC\'s professional network presence current automatically',
      'Google reCAPTCHA v2 on all public forms — reduces bot submissions for sensitive financial centre applications',
    ],
    tradeoffs: 'MySQL over PostgreSQL to match existing NIFC infrastructure. Added complexity of dual auth system vs. unified approach.',
    impact: 'Provides Kenya\'s premier financial centre with a professional digital platform. Handles institutional-grade security and compliance requirements.',
    stack: ['React 18', 'Vite 5', 'TailwindCSS', 'DaisyUI', 'Node.js', 'Express', 'MySQL 8', 'Microsoft Graph API'],
    lessonsLearned: 'Government and institutional projects have different quality bars. Documentation, audit trails, and security aren\'t optional — they\'re the entire product.',
    url: 'https://github.com/savin2001/nifca',
    planetSize: 2.2,
    planetColor: '#0EA5E9',
    orbitRadius: 12,
    orbitSpeed: 0.28,
  },
  {
    id: 'jenga-mkenya',
    name: 'Jenga Mkenya 2027',
    repo: 'revamped-donation-site',
    category: 'fintech',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    isPrivate: true,
    description: 'Multi-gateway donation platform built for Dr. Reuben Kigame\'s presidential campaign. Handles M-Pesa, Airtel Money, Stripe, Flutterwave, and bank transfers in a single checkout flow.',
    problem: 'Political donation platforms in Kenya are either foreign (card-only, inaccessible to most Kenyans) or crude M-Pesa paybill setups with no real UX. A campaign needed a serious, multi-gateway solution.',
    architecture: 'React 18 + Vite frontend, Node.js/Express serverless API on Vercel, Supabase PostgreSQL (schema: jenga_mkenya). Payment layer handles Safaricom Daraja (M-Pesa STK Push), Airtel Money/T-Kash/Equity EazzyPay via Flutterwave, Stripe Elements (PCI-DSS), and international methods. TanStack Query for server state, Zustand for UI.',
    keyDecisions: [
      'Safaricom Daraja STK Push as primary — real-time phone prompt, no USSD codes to memorise',
      'Flutterwave for alternative mobile money — covers Airtel, T-Kash, Equity in one integration',
      'Stripe for international donors — PCI-DSS compliant, familiar UX for diaspora',
      'Serverless-http wrapping Express — single backend codebase deploys as Vercel functions',
      '4-step donation wizard — breaks complex multi-payment flow into digestible steps',
    ],
    tradeoffs: 'Supporting 8+ payment methods multiplies testing surface area. Built an abstracted payment service layer to contain complexity.',
    impact: 'Made the campaign accessible to every Kenyan — phone, card, bank, or international wire.',
    stack: ['React 18', 'Vite 5', 'Node.js', 'Supabase', 'M-Pesa Daraja', 'Stripe', 'Flutterwave', 'TanStack Query'],
    lessonsLearned: 'Payment diversity is a social equity decision. Building M-Pesa first isn\'t just UX — it\'s the difference between accessible and exclusive.',
    url: 'https://github.com/savin2001/revamped-donation-site',
    planetSize: 2.0,
    planetColor: '#EC4899',
    orbitRadius: 14,
    orbitSpeed: 0.22,
  },
  {
    id: 'wrap-it',
    name: 'Wrap It! 2.0',
    repo: 'wrap-it',
    category: 'product',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    isPrivate: true,
    description: 'Sexual and reproductive health e-commerce + education platform for Kenya. Discreet product delivery, curated health articles, and an anonymous community Q&A — built to reduce stigma.',
    problem: 'Sexual health products are stigmatised in Kenya — people avoid pharmacies out of embarrassment. There was no discreet, trusted online option with local payment support and health education.',
    architecture: 'React 18 + Vite frontend, Node.js/Express 5 backend, Supabase (PostgreSQL + Auth + RLS). Shop, education hub, anonymous Q&A board, admin portal. M-PESA Daraja STK Push for checkout. Discreet packaging flag in order model. Supabase RLS enforces anonymous post isolation.',
    keyDecisions: [
      'Anonymous Q&A board — Supabase RLS ensures no user identity is exposed, even in admin view',
      'Discreet packaging as a first-class feature — not a checkbox, a UX centrepiece',
      'M-PESA STK Push — removes card requirement; critical for privacy (no statement entry)',
      'Admin moderation layer — safety and accuracy of community health content is non-negotiable',
      'Express 5 for async error handling — eliminates try/catch boilerplate across async routes',
    ],
    tradeoffs: 'Anonymous posts require extra moderation effort. Accepted operational cost to maintain user safety and trust.',
    impact: 'Reduces stigma around sexual health by creating a safe, discreet access point for products and education.',
    stack: ['React 18', 'Vite', 'Node.js', 'Express 5', 'Supabase', 'M-PESA Daraja', 'Tailwind CSS'],
    lessonsLearned: 'Privacy is a feature in health tech. Every data decision must be evaluated through: "could this expose or embarrass a user?"',
    url: 'https://github.com/savin2001/wrap-it',
    planetSize: 1.8,
    planetColor: '#A855F7',
    orbitRadius: 7,
    orbitSpeed: 0.45,
  },
  // ─── Core FinTech projects ────────────────────────────────────────
  {
    id: 'chapchapsms',
    name: 'ChapChapSMS',
    repo: 'chapchapsms-mvp',
    category: 'fintech',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    description: 'Multi-tenant bulk SMS platform for business communication at scale',
    problem: 'Small businesses in East Africa needed affordable, reliable mass communication infrastructure without complexity',
    architecture: 'Node.js + Express REST API, React dashboard, Africa\'s Talking SMS gateway, LowDB for rapid prototyping, queue-based message dispatch',
    keyDecisions: [
      'Africa\'s Talking over Twilio — 80% cost reduction for African carriers',
      'LowDB for MVP speed — zero infrastructure overhead at prototype stage',
      'Multi-tenant from day one — isolation and billing built-in',
      'Queue architecture — prevents API rate limit failures',
    ],
    tradeoffs: 'LowDB limits to ~10k records. Production migrates to PostgreSQL. Chose speed-to-market over scale.',
    impact: 'Enabled SMEs to dispatch thousands of SMS campaigns. Proved product-market fit for bulk messaging in East Africa.',
    stack: ['Node.js', 'Express', 'React', 'Tailwind CSS', 'Africa\'s Talking', 'LowDB'],
    lessonsLearned: 'Telco API quirks are unpredictable. Always build retry logic and dead-letter queues from day one.',
    url: 'https://github.com/savin2001/chapchapsms-mvp',
    planetSize: 2.2,
    planetColor: '#F59E0B',
    orbitRadius: 17,
    orbitSpeed: 0.32,
  },
  {
    id: 'nse-ai-tracker',
    name: 'NSE AI Research Platform',
    repo: 'nse-ai-tracker',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'AI-powered financial research platform for the Nairobi Securities Exchange. Claude generates BUY/HOLD/SELL signals with confidence scores, key factors, and target prices — with full prompt caching, AI security, and per-user cost controls.',
    problem: 'Retail NSE investors had no intelligent, affordable research tooling. Signals were either expensive Bloomberg-tier or gut-feel speculation. A production-grade AI analyst needed to be affordable at scale.',
    architecture: 'React 19/Vite 6 frontend + Node.js/Express 4 API + Python 3.11 workers on Vultr VPS. Python workers (ai_worker.py, signal_evaluator.py) call Claude Sonnet for BUY/HOLD/SELL signals and Claude Haiku for fast event classification. Prompt caching on the static 600-token system prompt saves ~75% on cache-read calls. Supabase PostgreSQL with RLS. GitHub Actions CI/CD with 6 workflows.',
    keyDecisions: [
      'Dual-model strategy: Claude Haiku (fast, $0.80/M) for event classification; Claude Sonnet (balanced, $3/M) for signal generation — optimises cost vs quality per task',
      'Prompt caching with cache_control: ephemeral on static system prompts — verified 75% cost reduction on dominant token path',
      'AI security middleware: prompt injection guard (regex + homoglyph normalisation), per-user rate limit (5 req/min), 50K daily token budget, in-flight request dedup',
      'Cost tracking table (model_usage): every Claude call logged with input/output/cache tokens and USD cost; admin analytics dashboard over 24h/7d/30d',
      'Circuit breaker on Anthropic API calls — prevents cascade failures from upstream latency spikes',
    ],
    tradeoffs: 'NSE data is semi-public; built legal scrapers + Python workers to ingest price, news, and macro data. Single-VPS state (in-process Maps) works for MVP; Redis needed for multi-instance AI rate limiting.',
    impact: 'Democratises institutional-quality market analysis for Kenyan retail investors. Runs at < $10/month infrastructure cost at launch.',
    stack: ['TypeScript', 'React 19', 'Node.js', 'Python 3.11', 'Claude API', 'Supabase', 'Vite 6', 'Recharts'],
    lessonsLearned: 'AI cost management is architecture, not config. Caching, model tiering, and spend guards need to be designed in from day one — not retrofitted.',
    url: 'https://github.com/savin2001/nse-ai-tracker',
    planetSize: 2.6,
    planetColor: '#0EA5E9',
    orbitRadius: 20,
    orbitSpeed: 0.24,
  },
  {
    id: 'gamified-devops',
    name: 'Gamified DevOps RPG',
    repo: 'Gamified-DevOps-RPG',
    category: 'infrastructure',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'RPG game that teaches DevOps concepts through interactive storytelling and real scenarios',
    problem: 'DevOps learning is abstract and dry. Engineers struggle to connect CI/CD theory to real-world operational pressure.',
    architecture: 'TypeScript game engine, scenario-based progression, on-call simulation mechanics, real DevOps concepts embedded in gameplay',
    keyDecisions: [
      'RPG genre — highest engagement for technical learning',
      'Scenario-based — mimics real on-call and deployment situations',
      'Progressive complexity — mirrors real DevOps maturity curve',
    ],
    tradeoffs: 'Game fidelity vs educational accuracy. Chose education first, gameplay second.',
    impact: 'Novel approach to DevOps education merging entertainment with operational training.',
    stack: ['TypeScript', 'React', 'Game Logic', 'GSAP'],
    lessonsLearned: 'Gamification works when game mechanics mirror the target skill, not just wrap it in a story.',
    url: 'https://github.com/savin2001/Gamified-DevOps-RPG',
    planetSize: 2.4,
    planetColor: '#10B981',
    orbitRadius: 23,
    orbitSpeed: 0.18,
  },
  {
    id: 'summit-nexus',
    name: 'Summit Nexus',
    repo: 'the-summit-nexus',
    category: 'product',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Executive intelligence platform delivering strategic insights for tech leaders',
    problem: 'Tech executives lacked a single platform aggregating industry signals, competitive intelligence, and strategic frameworks',
    architecture: 'TypeScript + Next.js, AI-driven content aggregation, executive-grade UX, real-time intelligence feeds, subscription management',
    keyDecisions: [
      'AI curation over manual editorial — scales without editorial team',
      'Executive UX — minimal, dense, no noise',
      'Subscription model — aligns incentives with content quality',
    ],
    tradeoffs: 'AI curation risks hallucination; implemented human-review layer for strategic content.',
    impact: 'Provides CTOs and VPs with curated intelligence for faster, better-informed decisions.',
    stack: ['TypeScript', 'Next.js', 'AI/LLM', 'Tailwind CSS'],
    lessonsLearned: 'Executive products must be ruthlessly focused. Every feature must earn its place.',
    url: 'https://github.com/savin2001/the-summit-nexus',
    planetSize: 2.6,
    planetColor: '#F59E0B',
    orbitRadius: 27,
    orbitSpeed: 0.14,
  },
  {
    id: 'grant-pilot',
    name: 'Grant Pilot Canada',
    repo: 'grant_pilot_canada',
    category: 'product',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'AI platform demystifying Canadian government grants for SMEs',
    problem: 'Canadian SMEs miss billions in available grants due to complex eligibility, jargon, and fragmented information',
    architecture: 'TypeScript + Next.js, AI eligibility matching engine, automated grant database updates, application workflow automation',
    keyDecisions: [
      'AI eligibility matching — no manual browsing of 500+ programs',
      'Plain-language translation — removes government jargon barrier',
      'Workflow automation — handles applications, not just discovery',
    ],
    tradeoffs: 'Grant data changes frequently; automated refresh pipeline is critical infrastructure.',
    impact: 'Helps SMEs discover and apply for grants they would otherwise miss.',
    stack: ['TypeScript', 'Next.js', 'AI/LLM', 'PostgreSQL'],
    lessonsLearned: 'Government data is messy. Budget 3x the time you think for data normalization.',
    url: 'https://github.com/savin2001/grant_pilot_canada',
    planetSize: 2.2,
    planetColor: '#EF4444',
    orbitRadius: 30,
    orbitSpeed: 0.11,
  },
  {
    id: 'devops-journey',
    name: 'DevOps Learning Journey',
    repo: 'devops-learning-journey',
    category: 'infrastructure',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 4,
    description: 'Documented journey through modern DevOps — real tools, real configs, real setups',
    problem: 'DevOps knowledge is scattered. This is a structured, documented path through real tools and real setups.',
    architecture: 'Python automation scripts, IaC examples, CI/CD templates, monitoring configurations, hands-on exercises',
    keyDecisions: [
      'Document everything — learning is only valuable if transferable',
      'Real tools only — no toy examples, actual production-grade configs',
      'Community-first — starred and forked by peers',
    ],
    tradeoffs: 'Breadth vs depth. Chose breadth to create a map, then depth on critical paths.',
    impact: '4 stars, 2 forks — actively used by community for learning.',
    stack: ['Python', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    lessonsLearned: 'Documenting your learning journey compounds knowledge and builds community simultaneously.',
    url: 'https://github.com/savin2001/devops-learning-journey',
    planetSize: 1.6,
    planetColor: '#3572A5',
    orbitRadius: 33,
    orbitSpeed: 0.08,
  },
  {
    id: 'n8n-automation',
    name: 'n8n Automation Stack',
    repo: 'my-n8n-docker',
    category: 'automation',
    language: 'Dockerfile',
    languageColor: '#2496ED',
    description: 'Self-hosted n8n workflow automation stack with Docker — zero vendor lock-in',
    problem: 'No-code automation platforms are expensive and lock you into vendor ecosystems',
    architecture: 'Docker Compose n8n stack, PostgreSQL persistence, reverse proxy, automated backup, custom workflow library',
    keyDecisions: [
      'Self-hosted n8n — zero vendor lock-in, data sovereignty',
      'Docker Compose — single-command deployment anywhere',
      'PostgreSQL backend — production-grade workflow storage',
    ],
    tradeoffs: 'Self-hosting requires maintenance. Chose control over convenience.',
    impact: 'Personal automation infrastructure running 50+ workflows.',
    stack: ['Docker', 'n8n', 'PostgreSQL', 'Nginx', 'Bash'],
    lessonsLearned: 'Self-hosted tooling pays dividends. Upfront investment eliminates recurring SaaS costs and vendor dependencies.',
    url: 'https://github.com/savin2001/my-n8n-docker',
    planetSize: 1.7,
    planetColor: '#EA4B71',
    orbitRadius: 36,
    orbitSpeed: 0.065,
  },
  {
    id: 'tax-automation',
    name: 'Tax Automation Platform',
    repo: 'tax-automation-platform',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Compliance platform helping Kenyan SMEs align with KRA tax requirements',
    problem: 'Kenyan SMEs face KRA compliance complexity without CFOs or tax software — resulting in penalties and legal risk',
    architecture: 'Subscription SaaS, automated tax computation, KRA eTIMS integration, compliance calendar, document generation',
    keyDecisions: [
      'KRA eTIMS integration — direct regulatory compliance',
      'Subscription model — recurring revenue aligned with continuous compliance',
      'Automated generation — removes manual calculation errors',
    ],
    tradeoffs: 'Regulatory APIs are unstable. Built extensive fallback and manual override systems.',
    impact: 'Removes compliance anxiety for SMEs operating in Kenya\'s tax environment.',
    stack: ['TypeScript', 'Next.js', 'KRA eTIMS API', 'PostgreSQL'],
    lessonsLearned: 'RegTech products must be bulletproof. Users trust you with their legal standing.',
    url: 'https://github.com/savin2001',
    planetSize: 2.0,
    planetColor: '#F59E0B',
    orbitRadius: 39,
    orbitSpeed: 0.055,
  },
  {
    id: 'sacco-ussd',
    name: 'Sacco USSD Platform',
    repo: 'sacco-ussd-platform',
    category: 'fintech',
    language: 'JavaScript',
    languageColor: '#F7DF1E',
    description: 'Banking access through low-bandwidth USSD channels for Kenyan Saccos',
    problem: 'Sacco members in rural Kenya cannot access accounts via smartphone apps — need low-bandwidth channel that works on feature phones',
    architecture: 'USSD state machine, Africa\'s Talking USSD gateway, session management, Sacco core banking integration',
    keyDecisions: [
      'USSD state machine architecture — maps perfectly to menu flows',
      'Session-less design — USSD sessions are ephemeral by nature',
      'Core banking adapter pattern — works with multiple Sacco systems',
    ],
    tradeoffs: 'USSD has 182-character limit per screen. Every word must count.',
    impact: 'Extends Sacco banking reach to feature phone users — the majority of rural Kenya.',
    stack: ['JavaScript', 'Node.js', 'Africa\'s Talking USSD', 'State Machine'],
    lessonsLearned: 'Constraint-driven design produces the clearest UX. USSD limits force clarity that smartphone apps often lack.',
    url: 'https://github.com/savin2001',
    planetSize: 1.9,
    planetColor: '#0D9488',
    orbitRadius: 42,
    orbitSpeed: 0.05,
  },
  {
    id: 'digital-farmers-wallet',
    name: 'Digital Farmers Wallet',
    repo: 'digital-farmers-wallet',
    category: 'fintech',
    language: 'TypeScript',
    languageColor: '#3178C6',
    description: 'Digital financial platform bringing banking services to agricultural communities',
    problem: 'Kenyan smallholder farmers are financially excluded — no savings vehicles, credit access, or payment rails',
    architecture: 'Mobile-first wallet, M-Pesa integration, savings circles, micro-loan engine, agent banking support, USSD fallback',
    keyDecisions: [
      'USSD + smartphone dual interface — serves all phone types in the market',
      'M-Pesa primary rails — where farmers already have money',
      'Agent banking model — trust through local intermediaries',
    ],
    tradeoffs: 'KYC requirements vs accessibility friction. Built tiered verification.',
    impact: 'Financial inclusion for underserved agricultural communities.',
    stack: ['TypeScript', 'React Native', 'M-Pesa API', 'USSD', 'PostgreSQL'],
    lessonsLearned: 'Financial products for underserved communities require radical simplicity and deep cultural understanding.',
    url: 'https://github.com/savin2001',
    planetSize: 1.9,
    planetColor: '#10B981',
    orbitRadius: 45,
    orbitSpeed: 0.045,
  },
]

export const services: Service[] = [
  {
    id: 'payment-infra',
    title: 'Payment Infrastructure',
    tagline: 'Move money reliably at scale',
    description: 'Design and build end-to-end payment systems — from M-Pesa integrations to multi-currency rails, reconciliation engines, and fraud detection.',
    deliverables: [
      'M-Pesa STK Push, B2C, C2B integrations',
      'Payment reconciliation and audit systems',
      'Multi-currency wallet architecture',
      'USSD banking channels for low-bandwidth users',
    ],
    industries: ['FinTech', 'SACCOs', 'NGOs', 'E-Commerce'],
    icon: '₿',
    accentColor: '#F59E0B',
  },
  {
    id: 'platform-engineering',
    title: 'Platform Engineering',
    tagline: 'Build once, scale forever',
    description: 'Architect multi-tenant SaaS platforms, API gateways, and microservices that grow with your business without rewrites.',
    deliverables: [
      'Multi-tenant SaaS architecture',
      'API gateway design and implementation',
      'Microservices decomposition',
      'Developer portal and SDK design',
    ],
    industries: ['SaaS', 'Enterprise', 'Startups', 'Marketplaces'],
    icon: '⬡',
    accentColor: '#0D9488',
  },
  {
    id: 'reliability-sre',
    title: 'Reliability Engineering',
    tagline: 'Systems that don\'t wake you up at 3am',
    description: 'Implement SRE practices, observability stacks, incident response playbooks, and reliability frameworks that keep your systems running.',
    deliverables: [
      'SLO/SLA definition and monitoring',
      'Prometheus + Grafana observability stack',
      'Incident response runbooks',
      'On-call rotation and escalation design',
    ],
    industries: ['All industries', 'Critical Infrastructure', 'FinTech'],
    icon: '▲',
    accentColor: '#10B981',
  },
  {
    id: 'digital-channels',
    title: 'Digital Channels',
    tagline: 'Meet your customers where they are',
    description: 'Build digital touchpoints across web, mobile, USSD, and SMS — ensuring your product reaches every user regardless of device or connectivity.',
    deliverables: [
      'USSD application design and development',
      'Bulk SMS campaign infrastructure',
      'Progressive web apps (PWA)',
      'Omnichannel notification systems',
    ],
    industries: ['FinTech', 'Telecoms', 'Government', 'NGOs'],
    icon: '◈',
    accentColor: '#0EA5E9',
  },
  {
    id: 'security-devops',
    title: 'Security & DevOps',
    tagline: 'Ship fast. Stay secure.',
    description: 'Implement DevSecOps pipelines, zero-trust architecture, and compliance frameworks that let you move fast without breaking trust.',
    deliverables: [
      'CI/CD pipeline security gates',
      'Zero-trust network architecture',
      'Secret management and rotation',
      'Compliance automation (SOC2, PCI-DSS)',
    ],
    industries: ['FinTech', 'Healthcare', 'Enterprise', 'Government'],
    icon: '⊛',
    accentColor: '#EF4444',
  },
]

export const careerStages: CareerStage[] = [
  {
    id: 'explore',
    title: 'EXPLORE',
    subtitle: 'Curiosity as Infrastructure',
    period: '2019 – 2020',
    description: 'First contact with systems. Learning that software is infrastructure, and infrastructure is everything. Building foundations through experimentation.',
    theme: 'from sketches to systems',
    accentColor: '#F59E0B',
    visual: 'sketch',
  },
  {
    id: 'build',
    title: 'BUILD',
    subtitle: 'Code Streams at Scale',
    period: '2020 – 2021',
    description: 'Turning ideas into production systems. First APIs, first databases, first customers. Learning that building is the fastest way to understand.',
    theme: 'from theory to production',
    accentColor: '#0EA5E9',
    visual: 'code',
  },
  {
    id: 'operate',
    title: 'OPERATE',
    subtitle: 'Reliability is a Feature',
    period: '2021 – 2022',
    description: 'Systems in production are systems under pressure. Learning monitoring, alerting, incident response. Uptime is trust.',
    theme: 'from code to confidence',
    accentColor: '#10B981',
    visual: 'dashboard',
  },
  {
    id: 'scale',
    title: 'SCALE',
    subtitle: 'Architecture at Volume',
    period: '2022 – 2023',
    description: 'Designing for 10x, 100x growth. Platform engineering, multi-tenant architecture, FinTech regulatory compliance. Every decision becomes leverage.',
    theme: 'from product to platform',
    accentColor: '#0D9488',
    visual: 'architecture',
  },
  {
    id: 'create',
    title: 'CREATE',
    subtitle: 'Systems Thinking as Product Design',
    period: '2023 – Now',
    description: 'Combining infrastructure depth with product intuition. Building digital channels, driving reliability engineering, pioneering FinTech. The future is still being written.',
    theme: 'from execution to vision',
    accentColor: '#F59E0B',
    visual: 'future',
  },
]

export const skills: SkillNode[] = [
  { id: 'kubernetes', label: 'Kubernetes', cluster: 'infrastructure', level: 3, connections: ['docker', 'helm', 'terraform', 'observability'] },
  { id: 'docker', label: 'Docker', cluster: 'infrastructure', level: 4, connections: ['kubernetes', 'ci-cd'] },
  { id: 'terraform', label: 'Terraform', cluster: 'infrastructure', level: 3, connections: ['kubernetes', 'aws', 'cloud'] },
  { id: 'helm', label: 'Helm', cluster: 'infrastructure', level: 3, connections: ['kubernetes'] },
  { id: 'ci-cd', label: 'CI/CD', cluster: 'infrastructure', level: 4, connections: ['docker', 'github-actions', 'devops'] },
  { id: 'github-actions', label: 'GitHub Actions', cluster: 'infrastructure', level: 4, connections: ['ci-cd'] },
  { id: 'security', label: 'Security', cluster: 'security', level: 4, connections: ['devsecops', 'zero-trust', 'iam'] },
  { id: 'devsecops', label: 'DevSecOps', cluster: 'security', level: 3, connections: ['security', 'ci-cd'] },
  { id: 'zero-trust', label: 'Zero Trust', cluster: 'security', level: 3, connections: ['security', 'iam'] },
  { id: 'iam', label: 'IAM', cluster: 'security', level: 3, connections: ['security', 'aws'] },
  { id: 'aws', label: 'AWS', cluster: 'cloud', level: 4, connections: ['terraform', 'cloud', 'iam'] },
  { id: 'cloud', label: 'Cloud Architecture', cluster: 'cloud', level: 4, connections: ['aws', 'kubernetes'] },
  { id: 'observability', label: 'Observability', cluster: 'observability', level: 4, connections: ['prometheus', 'grafana', 'reliability'] },
  { id: 'prometheus', label: 'Prometheus', cluster: 'observability', level: 3, connections: ['observability', 'grafana'] },
  { id: 'grafana', label: 'Grafana', cluster: 'observability', level: 3, connections: ['prometheus', 'observability'] },
  { id: 'reliability', label: 'SRE', cluster: 'observability', level: 4, connections: ['observability', 'devops'] },
  { id: 'devops', label: 'DevOps', cluster: 'automation', level: 5, connections: ['ci-cd', 'reliability', 'infrastructure', 'python'] },
  { id: 'python', label: 'Python', cluster: 'automation', level: 4, connections: ['devops', 'automation'] },
  { id: 'automation', label: 'Automation', cluster: 'automation', level: 4, connections: ['python', 'n8n'] },
  { id: 'n8n', label: 'n8n', cluster: 'automation', level: 3, connections: ['automation'] },
  { id: 'fintech', label: 'FinTech', cluster: 'fintech', level: 5, connections: ['mpesa', 'payments', 'ussd', 'compliance'] },
  { id: 'mpesa', label: 'M-Pesa API', cluster: 'fintech', level: 4, connections: ['fintech', 'payments'] },
  { id: 'payments', label: 'Payment Systems', cluster: 'fintech', level: 4, connections: ['fintech', 'mpesa'] },
  { id: 'ussd', label: 'USSD', cluster: 'fintech', level: 3, connections: ['fintech', 'telco'] },
  { id: 'compliance', label: 'Compliance', cluster: 'fintech', level: 3, connections: ['fintech', 'security'] },
  { id: 'telco', label: 'Telco APIs', cluster: 'fintech', level: 3, connections: ['ussd', 'sms'] },
  { id: 'sms', label: 'SMS Gateway', cluster: 'fintech', level: 3, connections: ['telco'] },
  { id: 'architecture', label: 'Architecture', cluster: 'architecture', level: 5, connections: ['microservices', 'api-design', 'cloud', 'devops'] },
  { id: 'microservices', label: 'Microservices', cluster: 'architecture', level: 4, connections: ['architecture', 'kubernetes'] },
  { id: 'api-design', label: 'API Design', cluster: 'architecture', level: 4, connections: ['architecture', 'nodejs'] },
  { id: 'typescript', label: 'TypeScript', cluster: 'code', level: 5, connections: ['nodejs', 'react', 'nextjs'] },
  { id: 'nodejs', label: 'Node.js', cluster: 'code', level: 5, connections: ['typescript', 'api-design'] },
  { id: 'react', label: 'React', cluster: 'code', level: 4, connections: ['typescript', 'nextjs'] },
  { id: 'nextjs', label: 'Next.js', cluster: 'code', level: 4, connections: ['react', 'typescript'] },
  // ─── AI Engineering cluster ───────────────────────────────────────────────
  { id: 'claude-api', label: 'Claude API', cluster: 'ai', level: 5, connections: ['prompt-eng', 'llm-ops', 'ai-safety', 'anthropic-sdk'] },
  { id: 'anthropic-sdk', label: 'Anthropic SDK', cluster: 'ai', level: 4, connections: ['claude-api', 'prompt-eng'] },
  { id: 'prompt-eng', label: 'Prompt Engineering', cluster: 'ai', level: 5, connections: ['claude-api', 'ai-safety', 'llm-ops'] },
  { id: 'prompt-caching', label: 'Prompt Caching', cluster: 'ai', level: 4, connections: ['claude-api', 'llm-ops'] },
  { id: 'llm-ops', label: 'LLM Ops', cluster: 'ai', level: 4, connections: ['prompt-eng', 'ai-safety', 'prompt-caching', 'python'] },
  { id: 'ai-safety', label: 'AI Safety', cluster: 'ai', level: 4, connections: ['prompt-eng', 'llm-ops', 'security'] },
  { id: 'ai-agents', label: 'AI Agents', cluster: 'ai', level: 4, connections: ['claude-api', 'automation', 'llm-ops'] },
  { id: 'rag', label: 'RAG', cluster: 'ai', level: 3, connections: ['claude-api', 'llm-ops'] },
]

export const clusterColors: Record<string, string> = {
  infrastructure: '#0EA5E9',
  security: '#EF4444',
  cloud: '#6366F1',
  observability: '#10B981',
  automation: '#F59E0B',
  fintech: '#0D9488',
  architecture: '#EC4899',
  code: '#F7DF1E',
  ai: '#A855F7',
}

export const metrics = {
  uptime: '99.97%',
  incidents_resolved: '147',
  deployments_shipped: '1,200+',
  systems_monitored: '35+',
  automation_workflows: '50+',
  repos: '66+',
  countries_impacted: '3',
}
